apiVersion: v1
kind: Service
metadata:
  name: vanity-robertsirre-nl-web
  namespace: vanity-robertsirre-nl
  labels:
    app: vanity-robertsirre-nl
    component: web
spec:
  type: ClusterIP # Changed to ClusterIP when using gateway as entry point
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: vanity-robertsirre-nl
    component: web
