apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanity-robertsirre-nl
  namespace: vanity-robertsirre-nl
  labels:
    app: vanity-robertsirre-nl
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vanity-robertsirre-nl
  template:
    metadata:
      labels:
        app: vanity-robertsirre-nl
    spec:
      containers:
      - name: web
        image: atreyu/naamnummer:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        # env:
        # - name: ASPNETCORE_ENVIRONMENT
        #   value: "Development"
        # - name: ASPNETCORE_URLS
        #   value: "http://0.0.0.0:5000/"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: vanity-robertsirre-nl
              topologyKey: kubernetes.io/hostname
